repos:
  - repo: local
    hooks:
      - id: format_svg
        name: Run format svg
        entry: bash -c "svgo --pretty -r -f ./"
        language: system
      - id: format_flutter
        name: Run flutter format
        entry: bash -c "flutter format --set-exit-if-changed ."
        language: system
      - id: format_flutter
        name: Run flutter analyze
        entry: bash -c "flutter analyze ."
        language: system
      - id: pod_install_ios
        name: Run pod install iOS
        entry: bash -c "cd ios; pod install"
        language: system
        files: ^ios/