repos:
  - repo: local
    hooks:
      - id: format_svg
        name: Run format svg
        entry: bash -c "svgo --pretty --disable=convertColors,removeViewBox --enable=removeDimensions,sortAttrs -r -f ./"
        language: system
        verbose: true
#      - id: pod_install_ios
#        name: Run pod install iOS
#        entry: bash -c "cd ios; pod install"
#        language: system
#        verbose: true