import glob
import os

# notesMap = {"A0": "21",
#             "Bb0": "22",
#             "B0": "23",
#             "C1": "24",
#             "Db1": "25",
#             "D1": "26",
#             "Eb1": "27",
#             "E1": "28",
#             "F1": "29",
#             "Gb1": "30",
#             "G1": "31",
#             "Ab1": "32",
#             "A1": "33",
#             "Bb1": "34",
#             "B1": "35",
#             "C2": "36",
#             "Db2": "37",
#             "D2": "38",
#             "Eb2": "39",
#             "E2": "40",
#             "F2": "41",
#             "Gb2": "42",
#             "G2": "43",
#             "Ab2": "44",
#             "A2": "45",
#             "Bb2": "46",
#             "B2": "47",
#             "C3": "48",
#             "Db3": "49",
#             "D3": "50",
#             "Eb3": "51",
#             "E3": "52",
#             "F3": "53",
#             "Gb3": "54",
#             "G3": "55",
#             "Ab3": "56",
#             "A3": "57",
#             "Bb3": "58",
#             "B3": "59",
#             "C4": "60",
#             "Db4": "61",
#             "D4": "62",
#             "Eb4": "63",
#             "E4": "64",
#             "F4": "65",
#             "Gb4": "66",
#             "G4": "67",
#             "Ab4": "68",
#             "A4": "69",
#             "Bb4": "70",
#             "B4": "71",
#             "C5": "72",
#             "Db5": "73",
#             "D5": "74",
#             "Eb5": "75",
#             "E5": "76",
#             "F5": "77",
#             "Gb5": "78",
#             "G5": "79",
#             "Ab5": "80",
#             "A5": "81",
#             "Bb5": "82",
#             "B5": "83",
#             "C6": "84",
#             "Db6": "85",
#             "D6": "86",
#             "Eb6": "87",
#             "E6": "88",
#             "F6": "89",
#             "Gb6": "90",
#             "G6": "91",
#             "Ab6": "92",
#             "A6": "93",
#             "Bb6": "94",
#             "B6": "95",
#             "C7": "96",
#             "Db7": "97",
#             "D7": "98",
#             "Eb7": "99",
#             "E7": "100",
#             "F7": "101",
#             "Gb7": "102",
#             "G7": "103",
#             "Ab7": "104",
#             "A7": "105",
#             "Bb7": "106",
#             "B7": "107",
#             "C8": "108",
#             }
notesMap = {"flute_A0_05_forte_normal": "21",
            "flute_As0_05_forte_normal": "22",
            "flute_B0_05_forte_normal": "23",
            "flute_C1_05_forte_normal": "24",
            "flute_Cs1_05_forte_normal": "25",
            "flute_D1_05_forte_normal": "26",
            "flute_Ds1_05_forte_normal": "27",
            "flute_E1_05_forte_normal": "28",
            "flute_F1_05_forte_normal": "29",
            "flute_Fs1_05_forte_normal": "30",
            "flute_G1_05_forte_normal": "31",
            "flute_Gs1_05_forte_normal": "32",
            "flute_A1_05_forte_normal": "33",
            "flute_As1_05_forte_normal": "34",
            "flute_B1_05_forte_normal": "35",
            "flute_C2_05_forte_normal": "36",
            "flute_Cs2_05_forte_normal": "37",
            "flute_D2_05_forte_normal": "38",
            "flute_Ds2_05_forte_normal": "39",
            "flute_E2_05_forte_normal": "40",
            "flute_F2_05_forte_normal": "41",
            "flute_Fs2_05_forte_normal": "42",
            "flute_G2_05_forte_normal": "43",
            "flute_Gs2_05_forte_normal": "44",
            "flute_A2_05_forte_normal": "45",
            "flute_As2_05_forte_normal": "46",
            "flute_B2_05_forte_normal": "47",
            "flute_C3_05_forte_normal": "48",
            "flute_Cs3_05_forte_normal": "49",
            "flute_D3_05_forte_normal": "50",
            "flute_Ds3_05_forte_normal": "51",
            "flute_E3_05_forte_normal": "52",
            "flute_F3_05_forte_normal": "53",
            "flute_Fs3_05_forte_normal": "54",
            "flute_G3_05_forte_normal": "55",
            "flute_Gs3_05_forte_normal": "56",
            "flute_A3_05_forte_normal": "57",
            "flute_As3_05_forte_normal": "58",
            "flute_B3_05_forte_normal": "59",
            "flute_C4_05_forte_normal": "60",
            "flute_Cs4_05_forte_normal": "61",
            "flute_D4_05_forte_normal": "62",
            "flute_Ds4_05_forte_normal": "63",
            "flute_E4_05_forte_normal": "64",
            "flute_F4_05_forte_normal": "65",
            "flute_Fs4_05_forte_normal": "66",
            "flute_G4_05_forte_normal": "67",
            "flute_Gs4_05_forte_normal": "68",
            "flute_A4_05_forte_normal": "69",
            "flute_As4_05_forte_normal": "70",
            "flute_B4_05_forte_normal": "71",
            "flute_C5_05_forte_normal": "72",
            "flute_Cs5_05_forte_normal": "73",
            "flute_D5_05_forte_normal": "74",
            "flute_Ds5_05_forte_normal": "75",
            "flute_E5_05_forte_normal": "76",
            "flute_F5_05_forte_normal": "77",
            "flute_Fs5_05_forte_normal": "78",
            "flute_G5_05_forte_normal": "79",
            "flute_Gs5_05_forte_normal": "80",
            "flute_A5_05_forte_normal": "81",
            "flute_As5_05_forte_normal": "82",
            "flute_B5_05_forte_normal": "83",
            "flute_C6_05_forte_normal": "84",
            "flute_Cs6_05_forte_normal": "85",
            "flute_D6_05_forte_normal": "86",
            "flute_Ds6_05_forte_normal": "87",
            "flute_E6_05_forte_normal": "88",
            "flute_F6_05_forte_normal": "89",
            "flute_Fs6_05_forte_normal": "90",
            "flute_G6_05_forte_normal": "91",
            "flute_Gs6_05_forte_normal": "92",
            "flute_A6_05_forte_normal": "93",
            "flute_As6_05_forte_normal": "94",
            "flute_B6_05_forte_normal": "95",
            "flute_C7_05_forte_normal": "96",
            "flute_Cs7_05_forte_normal": "97",
            "flute_D7_05_forte_normal": "98",
            "flute_Ds7_05_forte_normal": "99",
            "flute_E7_05_forte_normal": "100",
            "flute_F7_05_forte_normal": "101",
            "flute_Fs7_05_forte_normal": "102",
            "flute_G7_05_forte_normal": "103",
            "flute_Gs7_05_forte_normal": "104",
            "flute_A7_05_forte_normal": "105",
            "flute_As7_05_forte_normal": "106",
            "flute_B7_05_forte_normal": "107",
            "flute_C8_05_forte_normal": "108",
            }
# notesMap = {"violin_A0_1_piano_arco-normal": "21",
#             "violin_As0_1_piano_arco-normal": "22",
#             "violin_B0_1_piano_arco-normal": "23",
#             "violin_C1_1_piano_arco-normal": "24",
#             "violin_Cs1_1_piano_arco-normal": "25",
#             "violin_D1_1_piano_arco-normal": "26",
#             "violin_Ds1_1_piano_arco-normal": "27",
#             "violin_E1_1_piano_arco-normal": "28",
#             "violin_F1_1_piano_arco-normal": "29",
#             "violin_Fs1_1_piano_arco-normal": "30",
#             "violin_G1_1_piano_arco-normal": "31",
#             "violin_Gs1_1_piano_arco-normal": "32",
#             "violin_A1_1_piano_arco-normal": "33",
#             "violin_As1_1_piano_arco-normal": "34",
#             "violin_B1_1_piano_arco-normal": "35",
#             "violin_C2_1_piano_arco-normal": "36",
#             "violin_Cs2_1_piano_arco-normal": "37",
#             "violin_D2_1_piano_arco-normal": "38",
#             "violin_Ds2_1_piano_arco-normal": "39",
#             "violin_E2_1_piano_arco-normal": "40",
#             "violin_F2_1_piano_arco-normal": "41",
#             "violin_Fs2_1_piano_arco-normal": "42",
#             "violin_G2_1_piano_arco-normal": "43",
#             "violin_Gs2_1_piano_arco-normal": "44",
#             "violin_A2_1_piano_arco-normal": "45",
#             "violin_As2_1_piano_arco-normal": "46",
#             "violin_B2_1_piano_arco-normal": "47",
#             "violin_C3_1_piano_arco-normal": "48",
#             "violin_Cs3_1_piano_arco-normal": "49",
#             "violin_D3_1_piano_arco-normal": "50",
#             "violin_Ds3_1_piano_arco-normal": "51",
#             "violin_E3_1_piano_arco-normal": "52",
#             "violin_F3_1_piano_arco-normal": "53",
#             "violin_Fs3_1_piano_arco-normal": "54",
#             "violin_G3_1_piano_arco-normal": "55",
#             "violin_Gs3_1_piano_arco-normal": "56",
#             "violin_A3_1_piano_arco-normal": "57",
#             "violin_As3_1_piano_arco-normal": "58",
#             "violin_B3_1_piano_arco-normal": "59",
#             "violin_C4_1_piano_arco-normal": "60",
#             "violin_Cs4_1_piano_arco-normal": "61",
#             "violin_D4_1_piano_arco-normal": "62",
#             "violin_Ds4_1_piano_arco-normal": "63",
#             "violin_E4_1_piano_arco-normal": "64",
#             "violin_F4_1_piano_arco-normal": "65",
#             "violin_Fs4_1_piano_arco-normal": "66",
#             "violin_G4_1_piano_arco-normal": "67",
#             "violin_Gs4_1_piano_arco-normal": "68",
#             "violin_A4_1_piano_arco-normal": "69",
#             "violin_As4_1_piano_arco-normal": "70",
#             "violin_B4_1_piano_arco-normal": "71",
#             "violin_C5_1_piano_arco-normal": "72",
#             "violin_Cs5_1_piano_arco-normal": "73",
#             "violin_D5_1_piano_arco-normal": "74",
#             "violin_Ds5_1_piano_arco-normal": "75",
#             "violin_E5_1_piano_arco-normal": "76",
#             "violin_F5_1_piano_arco-normal": "77",
#             "violin_Fs5_1_piano_arco-normal": "78",
#             "violin_G5_1_piano_arco-normal": "79",
#             "violin_Gs5_1_piano_arco-normal": "80",
#             "violin_A5_1_piano_arco-normal": "81",
#             "violin_As5_1_piano_arco-normal": "82",
#             "violin_B5_1_piano_arco-normal": "83",
#             "violin_C6_1_piano_arco-normal": "84",
#             "violin_Cs6_1_piano_arco-normal": "85",
#             "violin_D6_1_piano_arco-normal": "86",
#             "violin_Ds6_1_piano_arco-normal": "87",
#             "violin_E6_1_piano_arco-normal": "88",
#             "violin_F6_1_piano_arco-normal": "89",
#             "violin_Fs6_1_piano_arco-normal": "90",
#             "violin_G6_1_piano_arco-normal": "91",
#             "violin_Gs6_1_piano_arco-normal": "92",
#             "violin_A6_1_piano_arco-normal": "93",
#             "violin_As6_1_piano_arco-normal": "94",
#             "violin_B6_1_piano_arco-normal": "95",
#             "violin_C7_1_piano_arco-normal": "96",
#             "violin_Cs7_1_piano_arco-normal": "97",
#             "violin_D7_1_piano_arco-normal": "98",
#             "violin_Ds7_1_piano_arco-normal": "99",
#             "violin_E7_1_piano_arco-normal": "100",
#             "violin_F7_1_piano_arco-normal": "101",
#             "violin_Fs7_1_piano_arco-normal": "102",
#             "violin_G7_1_piano_arco-normal": "103",
#             "violin_Gs7_1_piano_arco-normal": "104",
#             "violin_A7_1_piano_arco-normal": "105",
#             "violin_As7_1_piano_arco-normal": "106",
#             "violin_B7_1_piano_arco-normal": "107",
#             "violin_C8_1_piano_arco-normal": "108",
#             }
# notesMap = {"A0": "21",
#             "A#0": "22",
#             "B0": "23",
#             "C1": "24",
#             "C#1": "25",
#             "D1": "26",
#             "D#1": "27",
#             "E1": "28",
#             "F1": "29",
#             "F#1": "30",
#             "G1": "31",
#             "G#1": "32",
#             "A1": "33",
#             "A#1": "34",
#             "B1": "35",
#             "C2": "36",
#             "C#2": "37",
#             "D2": "38",
#             "D#2": "39",
#             "E2": "40",
#             "F2": "41",
#             "F#2": "42",
#             "G2": "43",
#             "G#2": "44",
#             "A2": "45",
#             "A#2": "46",
#             "B2": "47",
#             "C3": "48",
#             "C#3": "49",
#             "D3": "50",
#             "D#3": "51",
#             "E3": "52",
#             "F3": "53",
#             "F#3": "54",
#             "G3": "55",
#             "G#3": "56",
#             "A3": "57",
#             "A#3": "58",
#             "B3": "59",
#             "C4": "60",
#             "C#4": "61",
#             "D4": "62",
#             "D#4": "63",
#             "E4": "64",
#             "F4": "65",
#             "F#4": "66",
#             "G4": "67",
#             "G#4": "68",
#             "A4": "69",
#             "A#4": "70",
#             "B4": "71",
#             "C5": "72",
#             "C#5": "73",
#             "D5": "74",
#             "D#5": "75",
#             "E5": "76",
#             "F5": "77",
#             "F#5": "78",
#             "G5": "79",
#             "G#5": "80",
#             "A5": "81",
#             "A#5": "82",
#             "B5": "83",
#             "C6": "84",
#             "C#6": "85",
#             "D6": "86",
#             "D#6": "87",
#             "E6": "88",
#             "F6": "89",
#             "F#6": "90",
#             "G6": "91",
#             "G#6": "92",
#             "A6": "93",
#             "A#6": "94",
#             "B6": "95",
#             "C7": "96",
#             "C#7": "97",
#             "D7": "98",
#             "D#7": "99",
#             "E7": "100",
#             "F7": "101",
#             "F#7": "102",
#             "G7": "103",
#             "G#7": "104",
#             "A7": "105",
#             "A#7": "106",
#             "B7": "107",
#             "C8": "108",
#             }
for file in list(glob.glob("C:\\Users\\cuong\\Downloads\\violin\\*.mp3")):
    print(file)
    note = file.split("\\")[len(file.split("\\")) - 1].replace(".mp3", "").replace("Piano-", "")
    print(note)
    print(notesMap[note])
    os.rename(file, notesMap[note] + ".mp3")
