complexity:
  ComplexMethod:
    active: false
  LongMethod:
    active: false
    threshold: 60
  NestedBlockDepth:
    active: false
  TooManyFunctions:
    active: false
style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  ThrowsCount:
    active: false
performance:
  SpreadOperator:
    active: false