name: Build
'on':
  push:
    branches:
      - master
env:
  flutter_version: 2.2.2
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: '${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}'
      - name: Set up flutter
        # FIXME https://github.com/subosito/flutter-action/issues/105:
        uses: subosito/flutter-action@v1.5.1
        with:
          flutter-version: '${{ env.flutter_version }}'
      - name: Get dependencies
        run: flutter pub get
      - name: Format source code
        run: flutter format --set-exit-if-changed .
      - name: Analyze source code
        run: flutter analyze .
      - name: Add config files
        env:
          KEYSTORE_PROPERTIES: '${{ secrets.KEYSTORE_PROPERTIES }}'
          GOOGLE_SERVICES_STAGE_JSON: '${{ secrets.GOOGLE_SERVICES_STAGE_JSON }}'
          RELEASE_JKS: '${{ secrets.RELEASE_JKS }}'
        run: >
          sudo echo "$KEYSTORE_PROPERTIES" > android/keystore.properties

          sudo echo $GOOGLE_SERVICES_STAGE_JSON >
          android/app/src/stage/google-services.json

          sudo echo "$RELEASE_JKS" | base64 -d > android/release.jks
      - name: Build stage application
        run: >-
          flutter build apk --obfuscate
          --split-debug-info=build/app/outputs/symbols --flavor stage
          --split-per-abi
